export const tableAPPLList = {
  data: [
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc",
      exchange: "NASDAQ",
      mic_code: "XNGS",
      exchange_timezone: "America/New_York",
      instrument_type: "Common Stock",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc.",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "ARS",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc.",
      exchange: "BMV",
      mic_code: "XMEX",
      exchange_timezone: "America/Swift_Current",
      instrument_type: "Common Stock",
      country: "Mexico",
      currency: "MXN",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc",
      exchange: "BVC",
      mic_code: "XBOG",
      exchange_timezone: "America/New_York",
      instrument_type: "Common Stock",
      country: "Colombia",
      currency: "COP",
    },
    {
      symbol: "AAPLB",
      instrument_name: "APPLE INC",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "ARS",
    },
    {
      symbol: "AAPL34",
      instrument_name: "Apple Inc.",
      exchange: "Bovespa",
      mic_code: "BVMF",
      exchange_timezone: "America/Paramaribo",
      instrument_type: "Common Stock",
      country: "Brazil",
      currency: "BRL",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc.",
      exchange: "NEO",
      mic_code: "NEOE",
      exchange_timezone: "America/Toronto",
      instrument_type: "Common Stock",
      country: "Canada",
      currency: "CAD",
    },
    {
      symbol: "AAPLCL",
      instrument_name: "APPLE INC",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "CLP",
    },
    {
      symbol: "AAPLD",
      instrument_name: "APPLE INC",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "USD",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc",
      exchange: "BVL",
      mic_code: "XLIM",
      exchange_timezone: "America/Lima",
      instrument_type: "Common Stock",
      country: "Peru",
      currency: "PEN",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc.",
      exchange: "VSE",
      mic_code: "XWBO",
      exchange_timezone: "Europe/Vienna",
      instrument_type: "Common Stock",
      country: "Austria",
      currency: "EUR",
    },
    {
      symbol: "AAPLC",
      instrument_name: "APPLE INC",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "USD",
    },
    {
      symbol: "AAPL",
      instrument_name: "APPLE",
      exchange: "GPW",
      mic_code: "XWAR",
      exchange_timezone: "Europe/Warsaw",
      instrument_type: "Common Stock",
      country: "Poland",
      currency: "PLN",
    },
    {
      symbol: "AAPL",
      instrument_name: "Apple Inc.",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "USD",
    },
    {
      symbol: "AAPLBXX",
      instrument_name:
        "Royal Bank of Canada Capped Point to Point Buffer Note AAPLBXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLCXX",
      instrument_name:
        "Citigroup Global Markets Holdings Inc. Autocallable Contingent Interest Worst Of Barrier Note AAPLCX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLDXX",
      instrument_name:
        "Barclays Bank PLC Capped Point to Point Fully Principally Protected Note AAPLDXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLAXX",
      instrument_name:
        "Bank of Montreal Autocallable Contingent Interest Barrier Note AAPLAXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLEXX",
      instrument_name:
        "JPMorgan Chase Financial Company LLC Capped Point to Point Worst Of Buffer Note AAPLEXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLFXX",
      instrument_name:
        "Citigroup Global Markets Holdings Inc. Autocallable Point to Point Worst Of Barrier Note AAPLFXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLGXX",
      instrument_name:
        "Citigroup Global Markets Holdings Inc. Capped Point to Point Fully Principally Protected Note AAPLGX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLHXX",
      instrument_name:
        "JPMorgan Chase Financial Company LLC Capped Point to Point Fully Principally Protected Note AAPLHXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLIXX",
      instrument_name:
        "Barclays Bank PLC Point to Point Worst Of Buffer Note AAPLIXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLJXX",
      instrument_name:
        "JPMorgan Chase Financial Company LLC Point to Point Fully Principally Protected Note AAPLJXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLKXX",
      instrument_name:
        "JPMorgan Chase Financial Company LLC Capped Point to Point Fully Principally Protected Note AAPLKXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLLXX",
      instrument_name:
        "BofA Finance LLC Autocallable Snowball Worst Of Barrier Note AAPLLXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLMXX",
      instrument_name:
        "Citigroup Global Markets Holdings Inc. Autocallable Contingent Interest Barrier Note AAPLMXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLNXX",
      instrument_name:
        "BofA Finance LLC Autocallable Snowball Worst Of Barrier Note AAPLNXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLOXX",
      instrument_name: "Goldman Sachs Bank USA Point to Point CD AAPLOXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "AAPLPXX",
      instrument_name:
        "Goldman Sachs Bank USA Capped Point to Point CD AAPLPXX",
      exchange: "NASDAQ",
      mic_code: "XNAS",
      exchange_timezone: "America/New_York",
      instrument_type: "Mutual Fund",
      country: "United States",
      currency: "USD",
    },
  ],
  status: "ok",
};

export const tableGOOGLList = {
  data: [
    {
      symbol: "GOOGL",
      instrument_name: "Alphabet Inc",
      exchange: "NASDAQ",
      mic_code: "XNGS",
      exchange_timezone: "America/New_York",
      instrument_type: "Common Stock",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "GOOGL",
      instrument_name: "Alphabet Inc.",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "ARS",
    },
    {
      symbol: "GOOGL",
      instrument_name: "Alphabet Inc.",
      exchange: "BMV",
      mic_code: "XMEX",
      exchange_timezone: "America/Swift_Current",
      instrument_type: "Common Stock",
      country: "Mexico",
      currency: "MXN",
    },
    {
      symbol: "GOOGL",
      instrument_name: "Alphabet Inc",
      exchange: "BVL",
      mic_code: "XLIM",
      exchange_timezone: "America/Lima",
      instrument_type: "Common Stock",
      country: "Peru",
      currency: "PEN",
    },
    {
      symbol: "3LAL",
      instrument_name: "Granite  +3x GOOGL",
      exchange: "Euronext",
      mic_code: "XPAR",
      exchange_timezone: "Europe/Paris",
      instrument_type: "Common Stock",
      country: "France",
      currency: "EUR",
    },
    {
      symbol: "GOOGL",
      instrument_name: "Alphabet Inc.",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "USD",
    },
    {
      symbol: "3SAL",
      instrument_name: "Granite  -3x GOOGL",
      exchange: "Euronext",
      mic_code: "XPAR",
      exchange_timezone: "Europe/Paris",
      instrument_type: "Common Stock",
      country: "France",
      currency: "EUR",
    },
    {
      symbol: "GOOGLY",
      instrument_name: "Googly Cat",
      exchange: "",
      mic_code: "DIGITAL_CURRENCY",
      exchange_timezone: "UTC",
      instrument_type: "Digital Currency",
      country: "",
      currency: "",
    },
    {
      symbol: "GOOGLCL",
      instrument_name: "ALPHABET INC",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "CLP",
    },
  ],
  status: "ok",
};

export const tableMSFTList = {
  data: [
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corp",
      exchange: "NASDAQ",
      mic_code: "XNGS",
      exchange_timezone: "America/New_York",
      instrument_type: "Common Stock",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corporation",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "ARS",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corporation",
      exchange: "BMV",
      mic_code: "XMEX",
      exchange_timezone: "America/Swift_Current",
      instrument_type: "Common Stock",
      country: "Mexico",
      currency: "MXN",
    },
    {
      symbol: "MSFT34",
      instrument_name: "Microsoft Corporation",
      exchange: "Bovespa",
      mic_code: "BVMF",
      exchange_timezone: "America/Paramaribo",
      instrument_type: "Common Stock",
      country: "Brazil",
      currency: "BRL",
    },
    {
      symbol: "MSFTCL",
      instrument_name: "MICROSOFT CORP",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "CLP",
    },
    {
      symbol: "MSFT",
      instrument_name: "MICROSOFT CDR ",
      exchange: "NEO",
      mic_code: "NEOE",
      exchange_timezone: "America/Toronto",
      instrument_type: "Common Stock",
      country: "Canada",
      currency: "CAD",
    },
    {
      symbol: "MSFY",
      instrument_name: "Microsoft (MSFT) Yield Shares Purpose ETF",
      exchange: "NEO",
      mic_code: "NEOE",
      exchange_timezone: "America/Toronto",
      instrument_type: "Common Stock",
      country: "Canada",
      currency: "CAD",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corp",
      exchange: "BVL",
      mic_code: "XLIM",
      exchange_timezone: "America/Lima",
      instrument_type: "Common Stock",
      country: "Peru",
      currency: "PEN",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corporation",
      exchange: "VSE",
      mic_code: "XWBO",
      exchange_timezone: "Europe/Vienna",
      instrument_type: "Common Stock",
      country: "Austria",
      currency: "EUR",
    },
    {
      symbol: "MSFTD",
      instrument_name: "MICROSOFT CORP",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "USD",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corporation",
      exchange: "GPW",
      mic_code: "XWAR",
      exchange_timezone: "Europe/Warsaw",
      instrument_type: "Common Stock",
      country: "Poland",
      currency: "PLN",
    },
    {
      symbol: "1MSF",
      instrument_name: "1X MSFT",
      exchange: "Euronext",
      mic_code: "XPAR",
      exchange_timezone: "Europe/Paris",
      instrument_type: "Common Stock",
      country: "France",
      currency: "EUR",
    },
    {
      symbol: "MSFT",
      instrument_name: "LEVERAGE SHARES PUBLIC LIMITED ",
      exchange: "LSE",
      mic_code: "XLON",
      exchange_timezone: "Europe/London",
      instrument_type: "Common Stock",
      country: "United Kingdom",
      currency: "GBp",
    },
    {
      symbol: "PB2661",
      instrument_name: "BPA TB SH MSFT 300,0 B300,0 OP ",
      exchange: "MTA",
      mic_code: "XMIL",
      exchange_timezone: "Europe/Rome",
      instrument_type: "Common Stock",
      country: "Italy",
      currency: "EUR",
    },
    {
      symbol: "MSFT",
      instrument_name: "1X MSFT",
      exchange: "Euronext",
      mic_code: "XAMS",
      exchange_timezone: "Europe/Amsterdam",
      instrument_type: "Common Stock",
      country: "Netherlands",
      currency: "EUR",
    },
    {
      symbol: "MSFTC",
      instrument_name: "MICROSOFT CORP",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "USD",
    },
    {
      symbol: "MSFY",
      instrument_name: "IncomeShares Microsoft (MSFT) Options ETP",
      exchange: "LSE",
      mic_code: "XLON",
      exchange_timezone: "Europe/London",
      instrument_type: "Common Stock",
      country: "United Kingdom",
      currency: "USD",
    },
    {
      symbol: "3LMS",
      instrument_name: "Granite  +3x MSFT",
      exchange: "Euronext",
      mic_code: "XPAR",
      exchange_timezone: "Europe/Paris",
      instrument_type: "Common Stock",
      country: "France",
      currency: "EUR",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft Corporation",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "USD",
    },
    {
      symbol: "MSFT",
      instrument_name: "Microsoft 6900",
      exchange: "",
      mic_code: "DIGITAL_CURRENCY",
      exchange_timezone: "UTC",
      instrument_type: "Digital Currency",
      country: "",
      currency: "",
    },
    {
      symbol: "MSFTB",
      instrument_name: "MICROSOFT CORP",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "ARS",
    },
    {
      symbol: "3SMS",
      instrument_name: "Granite  -3x MSFT",
      exchange: "Euronext",
      mic_code: "XPAR",
      exchange_timezone: "Europe/Paris",
      instrument_type: "Common Stock",
      country: "France",
      currency: "EUR",
    },
  ],
  status: "ok",
};

export const tableNFLXList = {
  data: [
    {
      symbol: "NFLX",
      instrument_name: "Netflix Inc",
      exchange: "NASDAQ",
      mic_code: "XNGS",
      exchange_timezone: "America/New_York",
      instrument_type: "Common Stock",
      country: "United States",
      currency: "USD",
    },
    {
      symbol: "NFLX",
      instrument_name: "Netflix, Inc.",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "ARS",
    },
    {
      symbol: "NFLX",
      instrument_name: "Netflix, Inc.",
      exchange: "BMV",
      mic_code: "XMEX",
      exchange_timezone: "America/Swift_Current",
      instrument_type: "Common Stock",
      country: "Mexico",
      currency: "MXN",
    },
    {
      symbol: "NFLX34",
      instrument_name: "Netflix, Inc.",
      exchange: "Bovespa",
      mic_code: "BVMF",
      exchange_timezone: "America/Paramaribo",
      instrument_type: "Common Stock",
      country: "Brazil",
      currency: "BRL",
    },
    {
      symbol: "NFLX",
      instrument_name: "Netflix, Inc.",
      exchange: "NEO",
      mic_code: "NEOE",
      exchange_timezone: "America/Toronto",
      instrument_type: "Common Stock",
      country: "Canada",
      currency: "CAD",
    },
    {
      symbol: "NFLX",
      instrument_name: "Netflix, Inc.",
      exchange: "VSE",
      mic_code: "XWBO",
      exchange_timezone: "Europe/Vienna",
      instrument_type: "Common Stock",
      country: "Austria",
      currency: "EUR",
    },
    {
      symbol: "NFLXD",
      instrument_name: "NETFLIX INC",
      exchange: "BCBA",
      mic_code: "XBUE",
      exchange_timezone: "America/Argentina/Buenos_Aires",
      instrument_type: "Common Stock",
      country: "Argentina",
      currency: "USD",
    },
    {
      symbol: "1NFL",
      instrument_name: "1X NFLX",
      exchange: "Euronext",
      mic_code: "XPAR",
      exchange_timezone: "Europe/Paris",
      instrument_type: "Common Stock",
      country: "France",
      currency: "EUR",
    },
    {
      symbol: "NFLX",
      instrument_name: "Netflix Inc",
      exchange: "BVL",
      mic_code: "XLIM",
      exchange_timezone: "America/Lima",
      instrument_type: "Common Stock",
      country: "Peru",
      currency: "PEN",
    },
    {
      symbol: "NFLX",
      instrument_name: "NETFLIX",
      exchange: "GPW",
      mic_code: "XWAR",
      exchange_timezone: "Europe/Warsaw",
      instrument_type: "Common Stock",
      country: "Poland",
      currency: "PLN",
    },
    {
      symbol: "NFLX",
      instrument_name: "NETFLIX INC",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "USD",
    },
    {
      symbol: "NFLXCL",
      instrument_name: "NETFLIX INC",
      exchange: "BVS",
      mic_code: "XSGO",
      exchange_timezone: "America/Santiago",
      instrument_type: "Common Stock",
      country: "Chile",
      currency: "CLP",
    },
  ],
  status: "ok",
};
// https://api.twelvedata.com/symbol_search?symbol=AAPL&apikey=907b7a322df94f81bb4c652c04a6383f
